name: Autoblog Runner 24/7
on:
  schedule:
    - cron: '0 */5 * * *' # Ejecuta cada 2 horas
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install PyGithub google-genai youtube-transcript-api google-api-python-client python-slugify yt-dlp
      - run: python autoblog_100_master.py
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
